name: tfsec

on:
  push:
    branches: [ "develop" ]
  pull_request:
    paths:
      - '**/*.tf'
  schedule:
    - cron: '29 13 * * 1'

jobs:
  tfsec:
    name: Run tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec with SARIF output
        run: tfsec . --format sarif --out results.sarif --soft-fail=false

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
